posts/urls.py
from posts import views
from django.urls import path
from .views import (
	post_list,

	)
from django.conf.urls import url

app_name='post'

urlpatterns = [

    #
    path("", post_list, name = "index"),

    # path("", views.search(), name = "search"),

    path('<int:pk>/', views.Detailview.as_view(), name = "detail"),

    path('add/', views.PostCreate.as_view(), name='post-add'),

]

untitled/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, re_path
from django.contrib import admin
from  django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('posts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,default=1)
    title = models.CharField(max_length=125)
    content = models.TextField()
    post_image = models.ImageField()
    updated = models.DateTimeField(auto_now=True, auto_now_add= False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add= True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", "-updated"]

posts/views.py
from django.shortcuts import render
from django.views import generic
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.contrib.auth import  authenticate, login
from django.views.generic import  View

from posts.models import Post
from .models import Post
from django.utils import timezone

from django.db.models import Q, QuerySet


# from templates.posts import post_form.html

def post_list(request):

    blog_post = Post.objects.all()
    query = request.GET.get("q")
    if query:
        blog_post = blog_post.filter(Q(title__icontains=query)|
                                    Q(content__icontains=query)).distinct()
    paginator = Paginator(blog_post, 2)  # Show 25 contacts per page

    page = request.GET.get('page')
    all_posts = paginator.get_page(page)


    return render(request, 'posts/index.html', {'all_posts': all_posts})


class Detailview(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'




class PostCreate(CreateView):


    model = Post
    fields = ['title', 'content', 'post_image']
    # template_name = 'blog/post_form.html'

    success_url = reverse_lazy('post:index')

posts/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}Album Detail{% endblock %}

{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
        <div class="thumbnail">
        <img src="{{ post.post_image.url}}">
            </div>


        <h2>{{ post.title}}</h2>
        <h3>{{ post.content}}</h3>
{#        <h6>{{ request.build_absolute_uri }}</h6>#}

{#        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Share on Facebook</a>#}

        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>

    </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}


{% endblock %}

posts/templates/blog/index.html
{% extends 'blog/base.html' %}


{% block title %}Candid{% endblock %}
{% block body %}
    <div class="albums-container container-fluid">

    <!-- Albums -->
                <div class="row">

                    {% if all_posts %}
                        {% for post in all_posts %}
                            <div class="col-sm-6 col-sm-offset-3">


                                    <div class="caption">
                                        <div class="thumbnail">
                                            <img src="{{ post.post_image.url}}" class="img-responsive">
                                        </div>
                                        <h5>{{ post.title}}</h5>
                                        <h5>{{ post.updated}}</h5>
{#                                        <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>#}
{#                                        <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>#}
{#                                        <h6>{{ post.content }}</h6>#}
                                    </div>
                                    <!-- View Details -->
                                        <a href="{% url 'post:detail' post.id %}" class="btn btn-primary btn-sm" role="button">See Post</a>
                            <hr/>
                            </div>

                        {% endfor %}
                        <div class="col-sm-6 col-sm-offset-3">
                        <div class="pagination">
                            <span class="step-links">
                                {% if all_posts.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ all_posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ all_posts.number }} of {{ all_posts.paginator.num_pages }}.
                                </span>

                                {% if all_posts.has_next %}
                                    <a href="?page={{ all_posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                                    <a href="?page={{ all_posts.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                        </div>
                    {% endif %}

                </div>
    </div>
{% endblock %}

posts/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-7">
            <div class="panel panel-default">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>

                                <label class="control-label col-sm-2">
                                    {{ field.label_tag }}
                                </label>

                                <div class="col-sm-10">{{ field  }}</div>

                            </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Add Album</button>
                        </div>
                    </div>
                </form>



            </div>
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>


  {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet" type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}"/>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'blog/images/guest-blogger.png' %}" />
    <title>{% block title %}{% endblock %}</title>


</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'post:index' %} ">Candid</a>
        </div>

        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <form class="navbar-form navbar-left" role="search" method="GET" action="">

                    <div class="form-group">
                        <input type = "text" class="form-control" placeholder="Search Posts" name="q" value="{{ request.GET.q}}">
                    </div>

                    <button type="submit" value="Search" class="btn btn-default">Search</button>

                </form>


                <li class="active">
                   <a href="{% url 'post:index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                        Home
                     </a>
                </li>
                <li class="">
                    <a href="{% url 'post:post-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        New Post
                    </a>
                </li>

{#                <li class="">#}
{#                    <a href="#">#}
{#                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;#}
{#                        Timeline#}
{#                    </a>#}
{#                </li>#}

            </ul>

{#            <form  class="navbar-form navbar-left" role="search" method="get" action="#">#}
{#                <div class="form-group">#}
{#                    <input type = "text" class="form-control" name="q" value="">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Search</button>#}
{##}
{#            </form>#}
            <ul class="nav navbar-nav navbar-right">
{#                <li class="">#}
{#                    <a href="{% url 'music:album-add' %}">#}
{#                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;#}
{#                        Add Album#}
{#                    </a>#}
{#                </li>#}

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

  {% block body %}
  {% endblock %}


</body>
</html>

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}

{% block title %}Album Detail{% endblock %}

{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
        <div class="thumbnail">
        <img src="{{ post.post_image.url}}">
            </div>


        <h2>{{ post.title}}</h2>
        <h3>{{ post.content}}</h3>
{#        <h6>{{ request.build_absolute_uri }}</h6>#}

{#        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Share on Facebook</a>#}

        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>

    </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}


{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}


{% block title %}Candid{% endblock %}
{% block body %}
    <div class="albums-container container-fluid">

    <!-- Albums -->
                <div class="row">

                    {% if all_posts %}
                        {% for post in all_posts %}
                            <div class="col-sm-6 col-sm-offset-3">


                                    <div class="caption">
                                        <div class="thumbnail">
                                            <img src="{{ post.post_image.url}}" class="img-responsive">
                                        </div>
                                        <h5>{{ post.title}}</h5>
                                        <h5>{{ post.updated}}</h5>
{#                                        <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>#}
{#                                        <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>#}
{#                                        <h6>{{ post.content }}</h6>#}
                                    </div>
                                    <!-- View Details -->
                                        <a href="{% url 'post:detail' post.id %}" class="btn btn-primary btn-sm" role="button">See Post</a>
                            <hr/>
                            </div>

                        {% endfor %}
                        <div class="col-sm-6 col-sm-offset-3">
                        <div class="pagination">
                            <span class="step-links">
                                {% if all_posts.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ all_posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ all_posts.number }} of {{ all_posts.paginator.num_pages }}.
                                </span>

                                {% if all_posts.has_next %}
                                    <a href="?page={{ all_posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                                    <a href="?page={{ all_posts.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                        </div>
                    {% endif %}

                </div>
    </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-7">
            <div class="panel panel-default">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>

                                <label class="control-label col-sm-2">
                                    {{ field.label_tag }}
                                </label>

                                <div class="col-sm-10">{{ field  }}</div>

                            </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Add Album</button>
                        </div>
                    </div>
                </form>



            </div>
        </div>
    </div>
</div>
{% endblock %}